IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

LOAD DATASET

In [5]:
df = pd.read_csv("../dataset/Loan_default.csv")

In [6]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [7]:
df.shape

(255347, 18)

REMOVE LOANID

In [8]:
df.drop("LoanID", axis=1, inplace=True)

In [9]:
df.columns

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education',
       'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents',
       'LoanPurpose', 'HasCoSigner', 'Default'],
      dtype='object')

SEPERATED X AND Y

In [10]:
X = df.drop("Default", axis=1)
y = df["Default"]

In [11]:
print(X.shape)
print(y.shape)

(255347, 16)
(255347,)

In [12]:
X.columns

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education',
       'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents',
       'LoanPurpose', 'HasCoSigner'],
      dtype='object')

In [13]:
X.dtypes

Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education          object
EmploymentType     object
MaritalStatus      object
HasMortgage        object
HasDependents      object
LoanPurpose        object
HasCoSigner        object
dtype: object

In [14]:
categorical_cols = X.select_dtypes(include=["object"]).columns
numerical_cols = X.select_dtypes(exclude=["object"]).columns

print("Categorical Columns:")
print(categorical_cols)

print("\nNumerical Columns:")
print(numerical_cols)

Categorical Columns:
Index(['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
       'HasDependents', 'LoanPurpose', 'HasCoSigner'],
      dtype='object')

Numerical Columns:
Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio'],
      dtype='object')

In [15]:
for col in categorical_cols:
    print(f"\n{col}")
    print(X[col].unique())

Education
["Bachelor's" "Master's" 'High School' 'PhD']

EmploymentType
['Full-time' 'Unemployed' 'Self-employed' 'Part-time']

MaritalStatus
['Divorced' 'Married' 'Single']

HasMortgage
['Yes' 'No']

HasDependents
['Yes' 'No']

LoanPurpose
['Other' 'Auto' 'Business' 'Home' 'Education']

HasCoSigner
['Yes' 'No']

APPLIED LABLE ENCODING (CONVERT CETGORIES)

In [16]:
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    label_encoders[col] = le

In [17]:
X.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
0,56,85994,50587,520,80,4,15.23,36,0.44,0,0,0,1,1,4,1
1,69,50432,124440,458,15,1,4.81,60,0.68,2,0,1,0,0,4,1
2,46,84208,129188,451,26,3,21.17,24,0.31,2,3,0,1,1,0,0
3,32,31713,44799,743,0,3,7.07,24,0.23,1,0,1,0,0,1,0
4,60,20437,9139,633,8,4,6.51,48,0.73,0,3,0,0,1,0,0

In [18]:
X.dtypes

Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education           int64
EmploymentType      int64
MaritalStatus       int64
HasMortgage         int64
HasDependents       int64
LoanPurpose         int64
HasCoSigner         int64
dtype: object

In [19]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [20]:
X_scaled[:5]

array([[ 8.33989509e-01,  8.96928115e-02, -1.08683299e+00,
        -3.41492335e-01,  5.90533211e-01,  1.34193677e+00,
         2.61771239e-01, -1.52594275e-03, -2.60752922e-01,
        -1.33570762e+00, -1.34254075e+00, -1.22531495e+00,
         9.99972587e-01,  9.99463619e-01,  1.41535378e+00,
         9.99784630e-01],
       [ 1.70122109e+00, -8.23020714e-01, -4.43088703e-02,
        -7.31666109e-01, -1.28573104e+00, -1.34379144e+00,
        -1.30835003e+00,  1.41279312e+00,  7.78585323e-01,
         4.51884145e-01, -1.34254075e+00,  1.00779450e-04,
        -1.00002741e+00, -1.00053667e+00,  1.41535378e+00,
         9.99784630e-01],
       [ 1.66888295e-01,  4.38543784e-02,  2.27148729e-02,
        -7.75717987e-01, -9.68209399e-01,  4.46694036e-01,
         1.15683077e+00, -7.08685475e-01, -8.23727805e-01,
         4.51884145e-01,  1.34236901e+00, -1.22531495e+00,
         9.99972587e-01,  9.99463619e-01, -1.41606345e+00,
        -1.00021542e+00],
       [-7.67053404e-01, -1.30345164e+00, -1.16853758e+00,
         1.06187463e+00, -1.71871510e+00,  4.46694036e-01,
        -9.67805494e-01, -7.08685475e-01, -1.17017389e+00,
        -4.41911737e-01, -1.34254075e+00,  1.00779450e-04,
        -1.00002741e+00, -1.00053667e+00, -7.08209141e-01,
        -1.00021542e+00],
       [ 1.10082999e+00, -1.59285487e+00, -1.67192147e+00,
         3.69630835e-01, -1.48779027e+00,  1.34193677e+00,
        -1.05218821e+00,  7.05633590e-01,  9.95114124e-01,
        -1.33570762e+00,  1.34236901e+00, -1.22531495e+00,
        -1.00002741e+00,  9.99463619e-01, -1.41606345e+00,
        -1.00021542e+00]])

In [21]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
0,0.833990,0.089693,-1.086833,-0.341492,0.590533,1.341937,0.261771,-0.001526,-0.260753,-1.335708,-1.342541,-1.225315,0.999973,0.999464,1.415354,0.999785
1,1.701221,-0.823021,-0.044309,-0.731666,-1.285731,-1.343791,-1.308350,1.412793,0.778585,0.451884,-1.342541,0.000101,-1.000027,-1.000537,1.415354,0.999785
2,0.166888,0.043854,0.022715,-0.775718,-0.968209,0.446694,1.156831,-0.708685,-0.823728,0.451884,1.342369,-1.225315,0.999973,0.999464,-1.416063,-1.000215
3,-0.767053,-1.303452,-1.168538,1.061875,-1.718715,0.446694,-0.967805,-0.708685,-1.170174,-0.441912,-1.342541,0.000101,-1.000027,-1.000537,-0.708209,-1.000215
4,1.100830,-1.592855,-1.671921,0.369631,-1.487790,1.341937,-1.052188,0.705634,0.995114,-1.335708,1.342369,-1.225315,-1.000027,0.999464,-1.416063,-1.000215

In [22]:
X_scaled.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
count,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05,2.553470e+05
mean,-1.812065e-16,3.784411e-17,4.147548e-17,2.335205e-16,9.366418e-17,-2.983007e-17,1.408024e-16,1.861040e-16,5.253654e-17,-3.495015e-17,1.992381e-17,5.186870e-17,1.160924e-16,-7.323949e-17,3.895718e-17,-1.061861e-16
std,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00
min,-1.700995e+00,-1.732398e+00,-1.730348e+00,-1.725980e+00,-1.718715e+00,-1.343791e+00,-1.731770e+00,-1.415845e+00,-1.733149e+00,-1.335708e+00,-1.342541e+00,-1.225315e+00,-1.000027e+00,-1.000537e+00,-1.416063e+00,-1.000215e+00
25%,-8.337635e-01,-8.642522e-01,-8.670578e-01,-8.638217e-01,-8.527470e-01,-4.485487e-01,-8.623271e-01,-7.086855e-01,-8.670336e-01,-1.335708e+00,-4.475708e-01,-1.225315e+00,-1.000027e+00,-1.000537e+00,-7.082091e-01,-1.000215e+00
50%,-3.324207e-02,-8.547763e-04,-3.227743e-04,-1.663564e-03,1.322113e-02,-4.485487e-01,-4.938420e-03,-1.525943e-03,-9.183609e-04,-4.419117e-01,-4.475708e-01,1.007794e-04,9.999726e-01,9.994636e-01,-3.548323e-04,9.997846e-01
75%,8.339895e-01,8.654300e-01,8.668216e-01,8.667877e-01,8.791892e-01,4.466940e-01,8.675186e-01,7.056336e-01,8.651968e-01,4.518841e-01,4.473991e-01,1.225517e+00,9.999726e-01,9.994636e-01,7.074995e-01,9.997846e-01
max,1.701221e+00,1.732408e+00,1.728108e+00,1.728946e+00,1.716292e+00,1.341937e+00,1.733948e+00,1.412793e+00,1.731312e+00,1.345680e+00,1.342369e+00,1.225517e+00,9.999726e-01,9.994636e-01,1.415354e+00,9.997846e-01

SPLIT DATASET

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [24]:
print("Training Features:", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)
print("Testing Labels  :", y_test.shape)

Training Features: (204277, 16)
Testing Features : (51070, 16)
Training Labels : (204277,)
Testing Labels  : (51070,)

In [25]:
print("Training Set")
print(y_train.value_counts(normalize=True))

print("\nTesting Set")
print(y_test.value_counts(normalize=True))

Training Set
Default
0    0.883873
1    0.116127
Name: proportion, dtype: float64

Testing Set
Default
0    0.883865
1    0.116135
Name: proportion, dtype: float64

IMPORT JOBLIB (MODEL PERSISTENCE)

In [26]:
import joblib

In [27]:
joblib.dump(scaler, "../ml/scaler.pkl")

['../ml/scaler.pkl']

In [28]:
joblib.dump(label_encoders, "../ml/label_encoders.pkl")

['../ml/label_encoders.pkl']